blank_issues_enabled: false
contact_links:
  - name: NFT Community Support
    url: https://docs.google.com/forms/d/e/1FAIpQLScHSIF_NDSie-LU-CRmVW-mldSATJxOHKBfnDjJO7c4RaBlgw/viewform
    about: Please ask and answer general, non-bug related questions here.
