const contractAddress = "0x547cf2B9e3dB796315627c513Cd4C791D8395bD9"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the 8BitsDaddy Project!";
const welcome_h2 = "Connect to MetaMask to Get Started";
const welcome_p = 'Made by the a Team of Awesome Degen Dads';
const h1_presale_coming_soon = "NFT Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "We are working hard on the luanch. Wives and kids get in the way. DAD NFTs coming soon!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale..Bad Dad. 😢";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! You're an AWESOME Degen Daddy!🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Nice Try Dad.  🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! We welcome all Degen Dads to Mint! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special Degen Daddy NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. 😢 Please try again.";
